-- CREATE INDEX ON SCHOOL_ID.
CREATE INDEX SCHOOL_ID ON SCHOOL(SCHOOL_ID);

-- SEED the table from csv.
INSERT INTO SCHOOL(SCHOOL_ID, NAME, STATUS, SECTOR, TYPE, PHASE, SPECIALIZATION, EXAM_NO, PROVINCE,
    DISTRICT_MUNICIPALITY, LOCAL_MUNICIPALITY, POSTAL_CODE)
    (SELECT * FROM CSVREAD('src/main/resources/schools.csv'));

-- CREATE INDEX ON HOSPITAL_ID.
CREATE INDEX HOSPITAL_ID ON HOSPITAL(HOSPITAL_ID);

-- SEED the table from the csv.
INSERT INTO HOSPITAL(NAME, CATEGORY, PROVINCE, DISTRICT)
    (SELECT * FROM CSVREAD('src/main/resources/hospitals.csv'));