-- CREATE INDEX ON SCHOOL_ID.
CREATE INDEX SCHOOL_ID ON SCHOOL(SCHOOL_ID);

-- SEED the table from csv.
INSERT INTO SCHOOL(SCHOOL_ID, NAME, STATUS, SECTOR, TYPE, PHASE, SPECIALIZATION, EXAM_NO, PROVINCE,
    DISTRICT_MUNICIPALITY, LOCAL_MUNICIPALITY, POSTAL_CODE)
    (SELECT * FROM CSVREAD('src/main/resources/schools.csv'));

-- This should happen on load.
UPDATE SCHOOL
    SET POSTAL_CODE = NULL
    WHERE POSTAL_CODE = 0;

-- CREATE INDEX ON HOSPITAL_ID.
CREATE INDEX HOSPITAL_ID ON HOSPITAL(HOSPITAL_ID);

-- SEED the table from the csv.
INSERT INTO HOSPITAL(NAME, CATEGORY, PROVINCE, DISTRICT_MUNICIPALITY)
    (SELECT * FROM CSVREAD('src/main/resources/hospitals.csv'));