CREATE INDEX SCHOOL_ID ON SCHOOL(SCHOOL_ID);
--CREATE INDEX ID ON SCHOOL(ID)

INSERT INTO SCHOOL(SCHOOL_ID, NAME, STATUS, SECTOR, TYPE, PHASE, SPECIALIZATION, EXAM_NO, PROVINCE,
    DISTRICT_MUNICIPALITY, LOCAL_MUNICIPALITY, POSTAL_CODE)
    (SELECT * FROM CSVREAD('src/main/resources/schools.csv'));